### PR TITLE
Adds check for `subView` element in `renderSubview`

### PR DESCRIPTION
**Pull request by connor-ricks**
Amazing repo! Love the ease of use!

I did find a small crashing when using this repo.

1.) Each of my rows have a `status`
2.) Rows can swipe left, right or both depending on their status.

I encountered a sort of race condition in the following circumstance.

1.) Row has a hidden view
2.) Swipe out row to reveal hidden view
3.) Click hidden view (Action performed changes the status and that row no longer has a hidden view)
4.) React tries to clone a null `subView`

I solved this by checking to make sure we have a subView before we try to render it.

Would love to hear your thoughts!

### CODE REVIEW

**Comment by connor-ricks** [comment]
@andrewgrewell Just bumping! 😄

**Comment by andrewgrewell** [comment]
Thanks for the report @Zanchee, I'm not sure I follow 100%, can you post an example of what your swipelist/row data looks like?

**Comment by andrewgrewell** [comment]
I don't think there is any harm checking for this, but was just curious what this situation looked like. I imagine `leftSubView` or `rightSubView` is some type of value besides a react node, which should be giving props warnings.

Do you want to allow the row to be swiped when there is nothing being rendered?

**Comment by andrewgrewell** [comment]
Also I recently left the `ProvataHealth` org, so I will be a bit before I can merge this.

**Comment by andrewgrewell** [comment]
Going to merge this since it doesn't to have that protection, thanks for the PR!

**Comment by connor-ricks** [comment]
@andrewgrewell 

> I don't think there is any harm checking for this, but was just curious what this situation looked like. I imagine `leftSubView` or `rightSubView` is some type of value besides a react node, which should be giving props warnings.
> 
> Do you want to allow the row to be swiped when there is nothing being rendered?

My instance was that the `leftSubView` had a custom `View` component. but when tapped, it would re render the row without a `leftSubView` which in turn was causing the crash. I feel like it was some sort of race condition as it was only happening ~50% of the time. I tried it with an absolute bare basic project to make sure nothing was conflicting, but was still running into that issue. After adding this check, I haven't seen the issue arise again. 

A part of me does also want to be able to swipe the row, with tension, when there is no subview, that way the user knows that the rows are swipeable. This way, the user doesn't think they interacted with the row incorrectly, they just discover that there is nothing on that row to swipe.

Sorry for my delayed response! It's been a hectic week!

**Pull request merged**
